spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/order_master
    username: root
    password: Vissu408@@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
